name: Next.js CI + Deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build
      - run: npm run test --if-present

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "🔄 Deploying Preview to Vercel..."
            npx vercel --yes --token=${{ secrets.VERCEL_TOKEN }}
          else
            echo "🚀 Deploying Production to Vercel..."
            npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
